INSERT INTO book(id,isbn,title,price,description,nbofpage,illustrations) VALUES (10,'1234-56-8230', 'Web Programming Step by Step', 59.99, 'Programming web sites using HTML5, CSS3, PHP, MySQL', 620, 0)
INSERT INTO book(id,isbn,title,price,description,nbofpage,illustrations) VALUES (20,'7762-23-1042', 'Interact with Web Standards', 27.55, 'Introduction to Web Standards of HTML5, CSS3, and Javascript', 370, 1)
INSERT INTO book(id,isbn,title,price,description,nbofpage,illustrations) VALUES (30,'9126-77-3119', 'UML Distilled, Second edition', 19.99, 'Concise guide to modeling objects using UML', 148, 1)
INSERT INTO groups VALUES ('bookstore.user', 'authenticated user only')
INSERT INTO groups VALUES ('bookstore.manager', 'manager of the bookstore app')
INSERT INTO users(email, firstname, lastname, password) VALUES ('amonge@csulb.edu', 'Alvaro', 'Monge', '692d38c7336c857facb192d98c359154')
INSERT INTO users(email, firstname, lastname, password) VALUES ('tom@jewett.com', 'Tom', 'Jewett', '34b7da764b21d298ef307d04d8152dc5')
INSERT INTO groups_users(email, groupname) VALUES ('amonge@csulb.edu', 'bookstore.user')
INSERT INTO groups_users(email, groupname) VALUES ('amonge@csulb.edu', 'bookstore.manager')
INSERT INTO groups_users(email, groupname) VALUES ('tom@jewett.com', 'bookstore.user')
